from flask import Flask, request, jsonify
from flask_cors import CORS
from dotenv import load_dotenv
import os
import logging
from uuid import uuid4
from flasgger import Swagger

from .pipeline import run_pipeline
app = Flask(__name__)

# Load environment variables
load_dotenv()

CORS(app)

swagger = Swagger(app)

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def _format_elements(retrieved_documents):
    """
    Convert internal evidence entries into the simplified element payload expected by the UI.
    """
    elements = []
    for entry in retrieved_documents:
        document = (entry or {}).get("document") or {}
        metadata = (entry or {}).get("metadata") or {}
        resource_type = document.get("resource-type") or document.get("element_type")

        elements.append(
            {
                "_id": document.get("doc_id") or metadata.get("hit_id"),
                "_score": entry.get("score"),
                "contributor": document.get("contributor"),
                "contents": document.get("contents"),
                "resource-type": resource_type,
                "title": document.get("title"),
                "authors": document.get("authors") or [],
                "tags": document.get("tags") or [],
                "thumbnail-image": document.get("thumbnail-image") or document.get("thumbnail_image"),
            }
        )
    return elements


@app.route('/health', methods=['GET'])
def health():
    """Health check endpoint"""
    return jsonify({"status": "healthy", "service": "rag-pipeline"}), 200

@app.route('/query', methods=['POST'])
def query():
    """
Main RAG pipeline endpoint with LLM routing and optional reranking.

This endpoint accepts a natural language query and executes the full
retrieval-augmented generation (RAG) pipeline, including:
- retriever selection / routing
- optional LLM-based reranking
- context assembly
- answer synthesis
- trace and provenance collection

---
tags:
  - RAG
  - Query
consumes:
  - application/json
produces:
  - application/json

parameters:
  - in: body
    name: body
    required: true
    schema:
      type: object
      required:
        - user_input
      properties:
        user_input:
          type: string
          description: Natural language query from the user.
          example: "What is telecoupling in sustainability science?"
        memory_id:
          type: string
          nullable: true
          description: Optional session or memory identifier for conversational context.
          example: "session-abc123"
        params:
          type: object
          description: Parameters controlling retrieval and generation behavior.
          properties:
            top_k:
              type: integer
              default: 8
              description: Number of documents to retrieve.
            max_context_tokens:
              type: integer
              default: 6000
              description: Maximum token budget for assembled context.
            enable_llm_reranker:
              type: boolean
              default: true
              description: Whether to apply an LLM-based reranker to retrieved documents.
        session_context:
          type: object
          description: Arbitrary session-level context passed to the pipeline.
          example: {}
        recent_k:
          type: integer
          description: Number of recent conversational turns to include.
          example: 5
        extra_state:
          type: object
          description: Optional additional state injected into the pipeline.
          example: {}

responses:
  200:
    description: Query processed successfully.
    schema:
      type: object
      properties:
        answer:
          type: string
          description: Final composed answer generated by the RAG pipeline.
        message_id:
          type: string
          description: Unique identifier for this query-response pair.
        elements:
          type: array
          description: Retrieved and formatted evidence elements.
          items:
            type: object
        count:
          type: integer
          description: Number of retrieved evidence elements.
        retrievalSteps:
          type: array
          description: Retrieval routing and decision trace.
          items:
            type: object
        reactHistory:
          type: array
          description: ReAct-style reasoning or planner trace, if available.
          items:
            type: object

  400:
    description: Invalid request (e.g., missing user_input).
    schema:
      type: object
      properties:
        error:
          type: string

  500:
    description: Internal server error during pipeline execution.
    schema:
      type: object
      properties:
        error:
          type: string
"""

    try:
        data = request.get_json() or {}
        user_input = data.get('user_input')
        
        if not user_input:
            return jsonify({"error": "user_input is required"}), 400
        
        logger.info(f"Processing query: {user_input[:100]}...")
        
        # Run the full pipeline with LLM routing and reranker
        result = run_pipeline(
            user_input=user_input,
            memory_id=data.get('memory_id'),
            params=data.get('params', {
                "top_k": 8,
                "max_context_tokens": 6000,
                "enable_llm_reranker": True
            }),
            session_context=data.get('session_context', {}),
            recent_k=data.get('recent_k'),
            extra_state=data.get('extra_state', {})
        )
        
        evidence = result.get("evidence", {}) or {}
        retrieved_documents = evidence.get("retrieved_documents", []) or []
        elements = _format_elements(retrieved_documents)
        trace = result.get("trace_observability", {}) or {}
        planner = result.get("planner_reasoning", {}) or {}

        response = {
            "answer": (
                (result.get("answer") or {}).get("final_composed_answer")
                or "No answer"
            ),
            "message_id": str(uuid4()),
            "elements": elements,
            "count": len(elements),
            "retrievalSteps": trace.get("retrieval_routing_decisions") or [],
            "reactHistory": planner.get("react_history") or trace.get("react_history") or [],
        }
        
        logger.info(f"Query processed successfully. Retrieved {len(elements)} documents.")
        return jsonify(response), 200
        
    except ValueError as e:
        logger.error(f"Validation error: {str(e)}")
        return jsonify({"error": str(e)}), 400
    except Exception as e:
        logger.error(f"Error processing query: {str(e)}", exc_info=True)
        return jsonify({"error": f"Internal server error: {str(e)}"}), 500

@app.route('/query/batch', methods=['POST'])
def batch_query():
    """
    Batch query endpoint for processing multiple queries.
    
    Request body:
    {
        "queries": [
            {"user_input": "query 1", "memory_id": "session-1"},
            {"user_input": "query 2", "memory_id": "session-2"}
        ]
    }
    """
    try:
        data = request.get_json() or {}
        queries = data.get('queries', [])
        
        if not queries or not isinstance(queries, list):
            return jsonify({"error": "queries must be a non-empty list"}), 400
        
        results = []
        for query_data in queries:
            try:
                result = run_pipeline(
                    user_input=query_data.get('user_input'),
                    memory_id=query_data.get('memory_id'),
                    params=query_data.get('params', {}),
                    session_context=query_data.get('session_context', {})
                )
                results.append({
                    "success": True,
                    "answer": result.get("answer", {}),
                    "evidence": result.get("evidence", {})
                })
            except Exception as e:
                results.append({
                    "success": False,
                    "error": str(e)
                })
        
        return jsonify({"results": results}), 200
        
    except Exception as e:
        logger.error(f"Error processing batch query: {str(e)}", exc_info=True)
        return jsonify({"error": str(e)}), 500

if __name__ == '__main__':
    port = int(os.getenv('PORT', 5002))
    debug = os.getenv('DEBUG', 'false').lower() == 'true'
    app.run(host='0.0.0.0', port=port, debug=debug)
