FROM python:3.12-slim
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*
    
# Clone repository
WORKDIR /opt
RUN git clone https://github.com/I-GUIDE/i-guide-platform-flask-servers.git
    
# Set working directory
WORKDIR /opt/i-guide-platform-flask-servers/embedding-server
    
# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt
    
# Expose Flask port
EXPOSE 5000
    
# Start server
CMD ["python", "dense_embedding_server.py"]
    
